package ikabi.com.mobilesafe.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DLINK_DETAIL".
 */
public class DLinkDetail {

    private Long id;
    private String deviceId;
    private String createTime;

    public DLinkDetail() {
    }

    public DLinkDetail(Long id) {
        this.id = id;
    }

    public DLinkDetail(Long id, String deviceId, String createTime) {
        this.id = id;
        this.deviceId = deviceId;
        this.createTime = createTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDeviceId() {
        return deviceId;
    }

    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }

    public String getCreateTime() {
        return createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

}
